Aiplatf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView
from chatbotapp.views import chatbot

urlpatterns = [

    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('asks/', include('askapp.urls')),
    path('chatbot/', include('chatbotapp.urls')),


]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"


urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'),name='list'),

    path('create/', ArticleCreateView.as_view(),name='create'),

    path('detail/<int:pk>', ArticleDetailView.as_view(),name='detail'),

    # 몇번 article 로 가야 하는지 알려줘야 하기 때문에 <int:pk> 삽입
    path('update/<int:pk>', ArticleUpdateView.as_view(),name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(),name='delete'),
]

askapp/urls.py
from django.urls import path
from . import views

app_name = 'askapp'

urlpatterns = [
    path('write/', views.askwrite, name='askwrite'),
    path('list/', views.asklist, name='asklist'),
    # Add more URLs as needed
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models


# Create your models here.


class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)


from django.db import models

# Create your models here.

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models



# Create your models here.

class Article(models.Model):
    writer=models.ForeignKey(User,on_delete=models.SET_NULL,related_name='article',null=True)

    #writer=models.ForeignKey(User,on_delete=models.SET_NULL,related_name='article',null=True)
    # on_delete = models.SET_NULL 은 Article이 회원 탈퇴를 했을때 게시글이 사라지지 않고, 알 수 없음으로 주인없는 게시글이 되는걸로 설정한 것
    # article 이라는 이름으로 설정한 이유는 User에서 접근할 때 article이라고 하며 접근하는 것이 자연스럽다고 생각
    # SET_NULL로 설정을 앞에서 해줬기 때문에 null이 가능하도록 True값으로 설정

    title=models.CharField(max_length=200,null=True)
    image=models.ImageField(upload_to='article/',null=False) #False를 통해 이미지를 항상 넣도록 한다.
    content=models.TextField(null=True) # 좀더 긴 글을 적을 필요가 있으므로 CharField 보다는 TextField를 적용하였다.

    created_at = models.DateField(auto_now_add=True,null=True)
    # 언제 만들어 졌는지에 대한 정보 관련 코드, 자동 생성시에도 값이 저장되도록 하는 auto_created

    # 수정 : auto_new_add 로 변경하였는데 그 이유는 정상적으로 데이터가 쌓이게 되는 것이다.

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld


has_ownership = [account_ownership_required, login_required]
# Create your views here.

@login_required
def hello_world(request):
        if request.method == "POST":

            temp = request.POST.get('hello_world_input')

            new_hello_world = HelloWorld()
            new_hello_world.text = temp
            new_hello_world.save()
            return HttpResponseRedirect(reverse('accountapp:hello_world'))

        else:
            hello_world_list = HelloWorld.objects.all()
            return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})



class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 2rem auto;">
    <div class="mb-4">
      <h4>
        SignUp
      </h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method = "post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 2rem auto;">
    <div class="mb-4">
      <h4>
        Quit
      </h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method = "post">
      {% csrf_token %}
<!--      {{ form }}-->
      <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}
<style>
    .profile-container {
        text-align: center;
        max-width: 500px;
        margin: 4rem auto;
    }
    .profile-img {
        height: 15rem;
        width: 15rem;
        border-radius: 10rem;
        margin-bottom: 2rem;
    }
    .profile-nickname {
        font-family: 'MaruBuriBold.otf';
    }
    .profile-button {
        display: inline-block;
        margin-top: 1rem;
        padding: 5px 10px;
        font-size: 14px;
        border-radius: 5px;
        transition: background-color 0.3s;
    }
    .profile-button:hover {
        background-color: #0056b3;
        color: #fff;
    }
    .profile-message {
        margin-bottom: 3rem;
    }
    .profile-change {
        margin-top: 2rem;
    }
</style>

<div class="profile-container">
    <p>{{ target_user.date_joined }}</p>

    {% if target_user.profile %}
    <img src="{{ target_user.profile.image.url }}" alt="" class="profile-img">
    <h2 class="profile-nickname">
        {{ target_user.profile.nickname }}
        {% if target_user == user %}
        <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}" class="profile-button">
            Edit
        </a>
        {% endif %}
    </h2>
    <h5 class="profile-message">
        {{ target_user.profile.message }}
    </h5>
    {% else %}
    {% if target_user == user %}
    <a href="{% url 'profileapp:create' %}" class="profile-button">
        Create Profile
    </a>
    {% else %}
    <h2>
        Nickname Not Set
    </h2>
    {% endif %}
    {% endif %}

    {% if target_user == user %}
    <a href="{% url 'accountapp:update' pk=user.pk %}" class="profile-button profile-change">
        Change Info
    </a>
    <a href="{% url 'accountapp:delete' pk=user.pk %}" class="profile-button profile-change">
        Quit
    </a>
    {% endif %}
</div>
{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<style>
    .link-container {
        display: flex;
        justify-content: space-between;
        gap: 2.5rem;
        margin: 2rem 0;
    }

    .link-card {
        width: 100%;
        position: relative;
        background-color: #f0f4ff;
        border-radius: 1rem;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }

    .link-card-bg {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-image: url('pattern.svg');
        background-size: cover;
        background-position: right bottom;
        opacity: 0.1;
        border-radius: 1rem;
    }

    .link-content {
        padding: 1rem;
    }

    .link-title {
        font-weight: bold;
        font-size: 1.25rem;
    }

    .link-description {
        color: #6c757d;
    }

    .link-card:hover .link-title,
    .link-card:hover .link-description {
        color: #007bff;
    }
</style>

<div class="link-container">
    <a class="link-card" href="{% url 'articleapp:list' %}?next={{ request.path }}">
        <div class="link-card-bg"></div>
        <div class="link-content">
            <div class="link-title">커뮤니티</div>
        </div>
    </a>
    <div class="article-container">
    <div class="link-container">
        {% if article_list %}
        {% for article in article_list %}
            <a href="{% url 'articleapp:detail' pk=article.pk %}" class="article-card">
                <h3>{{ article.title }}</h3>
            </a>
        {% endfor %}
        {% else %}
            <div class="no-articles">No Articles Yet!</div>
        {% endif %}
    </div>
</div>

    <a class="link-card" href="{% url 'askapp:asklist' %}?next={{ request.path }}">
        <div class="link-card-bg"></div>
        <div class="link-content">
            <div class="link-title">Q&A</div>
        </div>
    </a>
</div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center;">
      <div>
        <h4>
          Login
        </h4>
      </div>
      <div style="text-align: center; max-width: 500px; margin: 2rem auto;">
        <form action="{% url 'accountapp:login' %}" method="post">
          {% csrf_token %}
<!--          {{ form }}-->
            {% bootstrap_form form %}
          <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
      </div>
  </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 2rem auto;">
    <div class="mb-4">
      <h4>
        SignUp
      </h4>
    </div>
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method = "post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}